### ISSUE TITLE
[Accepting friend request doesn't make the two friends]

### ISSUE THREAD

**Issue by rvvergara** [kvnlay/facemash#7]
I think we need to fix your implementation of creating friendships out of an existing friend_request.

Steps to recreate:

1. Create two users - `ryto` and `jim`
2. Run `jim.sent_requests.create(requested_id: ryto.id)`
3. Run `ryto.friends` -> Shows `jim` in it.
4. Run `jim.friends` -> Shows empty array. 

![image](https://user-images.githubusercontent.com/6015315/58550368-2ca46580-8240-11e9-9970-53b718821fd9.png)

This means

**Comment by kvnlay** [comment]
![Screen Shot 2019-05-29 at 12 06 04 PM](https://user-images.githubusercontent.com/21004010/58552817-36f83c80-820b-11e9-85fa-cffae6639502.png)
I followed the same steps you followed and both user `(u1 and u2)` friends array are populated respectively

**Comment by rvvergara** [comment]
Hi @kvnlay and @Cena-JM,

I guess I got confused with how we are implementing creating a friendship here. Perhaps I could recommend a simpler way:

- Perhaps we don't need the `accept_friend` method in `user.rb`. `ActiveRecord` 's creat method (inherited by your `friendship.rb` model) is already enough to handle creating friendships.

- In our `friendship.rb` we simply need to have a `private` method that we call `after_save` that deletes the associated `friend_requests` record anytime a `friendship` record is created. For instance, if there's a `friend_request` sent by `ryto` to `jim` then when later on `jim` clicks the `accept` button (consequently the `friendship` record is created/saved) then the `after_save` (or we can even do it `after_create`) callback will be triggered which will delete the `friend_request` sent by `ryto` to `jim`.

**Comment by rvvergara** [comment]
Wonderful job guys! I can close this now.. Everything is good on the friendship and request parts
